# -*- coding: utf-8 -*-

{
    'name': 'Job Card Extension',
    'category': 'Services/Project',
    'version': '15.0.1.0.1',
    'author': 'Sapna Verma',
    'company': '',
    'maintainer': 'Sapna Verma',
    'website': '',
    'summary': 'Job Card Extension',
    'images': [],
    'description': "Job Card Extension",
    'depends': ['project', 'job_card', 'base', 'account', 'customization_carzone', 'board', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/customer_declaration.xml',
        'views/job_card_views.xml',
        'views/res_partner_views.xml',
        'views/report_jobcard_views.xml',
        'views/repair_estimate_report_view.xml',
        'views/account_report.xml',
        #'views/job_card_dashboard.xml',
        'views/job_card_payment_views.xml',
        'views/timesheet_views.xml',
        'views/sale_order_views.xml',
    ],
    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
