
{
    'name': 'Formatted Reports',
    'version': '15.0.1.0.0',
    'category': 'Purchase',
    'summary': """Formatted Reports""",
    'description': "Formatted Reports for purchase and sales",
    'author': 'Jaimik Panchal',
    'website': "",
    'company': '',
    'maintainer': 'Jaimik Panchal',
    'depends': ['base', 'purchase', 'web', 'account', 'sale', 'project'],
    'data': [
        'views/res_partner_views.xml',
        'views/res_bank_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/res_company_views.xml',
        'views/report_templates.xml',
        'views/purchase_reports.xml',
        'views/account_reports.xml',
        'views/sale_reports.xml',
    ],
    'assets': {},
    'license': 'LGPL-3',
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
