from . import university_student
from . import university_course
from . import university_batch
#from . import university_department
from . import university_subject
from . import university_faculty
from . import university_admission
from . import assignment_type
from . import university_assignment
from . import attendance_register
from . import student_attendance
from . import exam_type
from . import exam_center_room_block
from . import university_exam
from . import parent_relationship
from . import parent_student
from . import result_template
from . import student_marksheet
from . import library_card
from . import library_book_author
from . import library_book_publisher
from . import library_media
